In [3]:
import pandas as pd
s = pd.Series([10, 20, 30, 40], index=["a", "b", "c", "d"])
print(s)

a    10
b    20
c    30
d    40
dtype: int64

In [4]:
data = {
"Возраст": [25, 30, 22],
"Город": ["Москва", "СПб", "Казань"]
}
df = pd.DataFrame(data, index=["Анна", "Иван", "Ольга"])
print(df)

       Возраст   Город
Анна        25  Москва
Иван        30     СПб
Ольга       22  Казань

In [5]:
print(df["Возраст"])

Анна     25
Иван     30
Ольга    22
Name: Возраст, dtype: int64

In [6]:
s = pd.Series([10, 20, 30], index=["a", "b", "c"])
df = s.to_frame(name="Значение")
print(df)

   Значение
a        10
b        20
c        30

In [7]:
s = df["Значение"]
print(s)

a    10
b    20
c    30
Name: Значение, dtype: int64

In [8]:
import pandas as pd
data = {
"Имя": ["Анна", "Иван", "Ольга"],
"Возраст": [25, 30, 22],
"Город": ["Москва", "СПб", "Казань"]
}
df = pd.DataFrame(data)
print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [9]:
ages = pd.Series([25, 30, 22], index=["a", "b", "c"])
cities = pd.Series(["Москва", "СПб", "Казань"], index=["a", "b", "c"])
df = pd.DataFrame({"Возраст": ages, "Город": cities})
print(df)

   Возраст   Город
a       25  Москва
b       30     СПб
c       22  Казань

In [10]:
data = [
["Анна", 25, "Москва"],
["Иван", 30, "СПб"],
["Ольга", 22, "Казань"]
]
df = pd.DataFrame(data, columns=["Имя", "Возраст", "Город"])
print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [11]:
data = [
{"Имя": "Анна", "Возраст": 25, "Город": "Москва"},
{"Имя": "Иван", "Возраст": 30}, # "Город" пропущен
{"Имя": "Ольга", "Возраст": 22, "Город": "Казань"}
]
df = pd.DataFrame(data)
print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     NaN
2  Ольга       22  Казань

In [14]:
import numpy as np
data = np.array([
["Анна", 25, "Москва"],
["Иван", 30, "СПб"],
["Ольга", 22, "Казань"]
])
df = pd.DataFrame(data, columns=["Имя", "Возраст", "Город"])
print(df)

     Имя Возраст   Город
0   Анна      25  Москва
1   Иван      30     СПб
2  Ольга      22  Казань

In [15]:
numeric_data = np.array([
[25, 65.5],
[30, 78.2],
[22, 54.3]
])
df = pd.DataFrame(numeric_data, columns=["Возраст", "Вес"])
print(df)

   Возраст   Вес
0     25.0  65.5
1     30.0  78.2
2     22.0  54.3

In [16]:
df = pd.DataFrame(columns=["Имя", "Возраст", "Город"])
print(df)

Empty DataFrame
Columns: [Имя, Возраст, Город]
Index: []

In [17]:
df.loc[0] = ["Анна", 25, "Москва"]
df.loc[1] = ["Иван", 30, "СПб"]
print(df)

    Имя  Возраст   Город
0  Анна       25  Москва
1  Иван       30     СПб

In [20]:
import pandas as pd
df = pd.read_csv("datapr.csv")
print(df.head()) # Выведем первые 5 строк

         Дата  Цена
0  2024-03-01   100
1  2024-03-02   110
2  2024-03-03   105
3  2024-03-04   120
4  2024-03-05   115

In [22]:
df = pd.read_csv("datapr.csv", sep=";", index_col=0, na_values=["?",
"N/A"])

In [26]:
df.to_csv("output.csv", index=False) # index=False — не сохранять индексы

In [33]:
data = {
    "Имя": ["Анна", "Иван", "Мария"],
    "Возраст": [25, 30, 28],
    "Город": ["Москва", "Санкт-Петербург", "Казань"]
}

# Преобразуем данные в DataFrame
df = pd.DataFrame(data)

# Сохраняем в Excel-файл (указываем движок openpyxl для .xlsx)
df.to_excel("datapr.xlsx", index=False, engine="openpyxl", sheet_name="Лист1")
df = pd.read_excel("datapr.xlsx", sheet_name="Лист1",engine='openpyxl')
print(df.head())

     Имя  Возраст            Город
0   Анна       25           Москва
1   Иван       30  Санкт-Петербург
2  Мария       28           Казань

In [43]:
data=[
{"Имя": "Анна", "Возраст": 25, "Город": "Москва"},
{"Имя": "Иван", "Возраст": 30, "Город": "СПб"},
{"Имя": "Ольга", "Возраст": 22, "Город": "Казань"}
]

df= pd.DataFrame(data)

df.to_json("output.json", orient="records", indent=4)

df = pd.read_json("output.json")
print(df.head())

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [46]:
data=[
{"Имя": "Анна", "Возраст": 25, "Город": "Москва"},
{"Имя": "Иван", "Возраст": 30, "Город": "СПб"},
{"Имя": "Ольга", "Возраст": 22, "Город": "Казань"}
]

df= pd.DataFrame(data)

df.to_parquet("output.parquet", engine="pyarrow", index=False)

df = pd.read_parquet("output.parquet")
print(df.head())

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [49]:
import sqlite3
data=[
{"Имя": "Анна", "Возраст": 25, "Город": "Москва"},
{"Имя": "Иван", "Возраст": 30, "Город": "СПб"},
{"Имя": "Ольга", "Возраст": 22, "Город": "Казань"}
]

df= pd.DataFrame(data)

df.to_sql("users", conn, if_exists="replace", index=False)

conn = sqlite3.connect("database.db") # Подключение к базе данных
query = "SELECT * FROM users"
df = pd.read_sql(query, conn)
print(df.head())

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [50]:
import pandas as pd
# Создадим небольшой DataFrame
data = {
"Имя": ["Анна", "Иван", "Ольга", "Петр", "Мария", "Сергей"],
"Возраст": [25, 30, 22, 40, 35, 28],
"Город": ["Москва", "СПб", "Казань", "Новосибирск",
"Екатеринбург", "Сочи"]
}
df = pd.DataFrame(data)
# Выведем первые 3 строки
print(df.head(3))

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [51]:
print(df.tail(2)) # Последние 2 строки

      Имя  Возраст         Город
4   Мария       35  Екатеринбург
5  Сергей       28          Сочи

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Имя      6 non-null      object
 1   Возраст  6 non-null      int64
 2   Город    6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

In [53]:
print(df.describe())

        Возраст
count   6.00000
mean   30.00000
std     6.60303
min    22.00000
25%    25.75000
50%    29.00000
75%    33.75000
max    40.00000

In [54]:
print(df.describe(include="object"))

         Имя   Город
count      6       6
unique     6       6
top     Анна  Москва
freq       1       1

In [55]:
import pandas as pd
data = {
"Имя": ["Анна", "Иван", "Ольга", "Петр"],
"Возраст": [25, 30, 22, 40],
"Город": ["Москва", "СПб", "Казань", "Новосибирск"]
}
df = pd.DataFrame(data, index=["a", "b", "c", "d"])
print(df)

     Имя  Возраст        Город
a   Анна       25       Москва
b   Иван       30          СПб
c  Ольга       22       Казань
d   Петр       40  Новосибирск

In [56]:
print(df.loc["b"])

Имя        Иван
Возраст      30
Город       СПб
Name: b, dtype: object

In [57]:
print(df.loc["c", "Город"]) # Получим город Ольги

Казань

In [58]:
print(df.loc[["a", "c"]]) # Выбор строк "a" и "c"

     Имя  Возраст   Город
a   Анна       25  Москва
c  Ольга       22  Казань

In [60]:
print(df.loc[:, ["Имя", "Город"]]) # Выбор всех строк, но только двух столбцов

     Имя        Город
a   Анна       Москва
b   Иван          СПб
c  Ольга       Казань
d   Петр  Новосибирск

In [62]:
print(df.loc[df["Возраст"] > 25]) # Выведем строки, где возраст больше 25

    Имя  Возраст        Город
b  Иван       30          СПб
d  Петр       40  Новосибирск

In [63]:
print(df.iloc[1]) # Вторая строка (нумерация с 0)

Имя        Иван
Возраст      30
Город       СПб
Name: b, dtype: object

In [64]:
print(df.iloc[2, 2]) # 3-я строка, 3-й столбец (Город Ольги)

Казань

In [65]:
print(df.iloc[[0, 2]]) # Строки 0 и 2 (Анна и Ольга)

     Имя  Возраст   Город
a   Анна       25  Москва
c  Ольга       22  Казань

In [66]:
print(df.iloc[1:3]) # Выбираем строки с 1 по 2 (не включая 3)

     Имя  Возраст   Город
b   Иван       30     СПб
c  Ольга       22  Казань

In [67]:
print(df.iloc[:, [0, 2]]) # Все строки, но только 1-й и 3-й столбцы

     Имя        Город
a   Анна       Москва
b   Иван          СПб
c  Ольга       Казань
d   Петр  Новосибирск

In [68]:
print(df.at["c", "Город"]) # Город Ольги

Казань

In [69]:
print(df.iat[2, 2]) # Город Ольги (3-я строка, 3-й столбец)

Казань

In [70]:
import pandas as pd
data = {
"Имя": ["Анна", "Иван", "Ольга"],
"Возраст": [25, 30, 22]
}
df = pd.DataFrame(data)
df["Город"] = ["Москва", "СПб", "Казань"] # Добавляем новый столбец
print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [71]:
df["Страна"] = "Россия"
print(df)

     Имя  Возраст   Город  Страна
0   Анна       25  Москва  Россия
1   Иван       30     СПб  Россия
2  Ольга       22  Казань  Россия

In [73]:
df["Возраст_в_месяцах"] = df["Возраст"] * 12
print(df)

     Имя  Возраст   Город  Страна  Возраст_в_месяцах
0   Анна       25  Москва  Россия                300
1   Иван       30     СПб  Россия                360
2  Ольга       22  Казань  Россия                264

In [74]:
df = df.assign(Зарплата=[50000, 60000, 45000])
print(df)

     Имя  Возраст   Город  Страна  Возраст_в_месяцах  Зарплата
0   Анна       25  Москва  Россия                300     50000
1   Иван       30     СПб  Россия                360     60000
2  Ольга       22  Казань  Россия                264     45000

In [75]:
df["Категория возраста"] = df["Возраст"].apply(lambda x: "Молодой" if
x < 30 else "Взрослый")
print(df)

     Имя  Возраст   Город  Страна  Возраст_в_месяцах  Зарплата  \
0   Анна       25  Москва  Россия                300     50000
1   Иван       30     СПб  Россия                360     60000
2  Ольга       22  Казань  Россия                264     45000

  Категория возраста
0            Молодой
1           Взрослый
2            Молодой

In [85]:
df.loc[3] = ["Петр", 40, "Новосибирск", "Россия", 5000, 797, "Молодой"]
print(df)

     Имя  Возраст        Город  Страна  Возраст_в_месяцах  Зарплата  \
0   Анна       25       Москва  Россия                300     50000
1   Иван       30          СПб  Россия                360     60000
2  Ольга       22       Казань  Россия                264     45000
3   Петр       40  Новосибирск  Россия               5000       797

  Категория возраста
0            Молодой
1           Взрослый
2            Молодой
3            Молодой

In [89]:
new_row = {"Имя": "Сергей", "Возраст": 35, "Город": "Сочи", "Страна":
"Россия"}
df = df.append(new_row, ignore_index=True)
print(df)

AttributeError: 'DataFrame' object has no attribute 'append'

In [90]:
new_data = pd.DataFrame([{"Имя": "Алексей", "Возраст": 29, "Город":
"Томск", "Страна": "Россия"}])
df = pd.concat([df, new_data], ignore_index=True)
print(df)

       Имя  Возраст        Город  Страна  Возраст_в_месяцах  Зарплата  \
0     Анна       25       Москва  Россия              300.0   50000.0
1     Иван       30          СПб  Россия              360.0   60000.0
2    Ольга       22       Казань  Россия              264.0   45000.0
3     Петр       40  Новосибирск  Россия             5000.0     797.0
4  Алексей       29        Томск  Россия                NaN       NaN

  Категория возраста
0            Молодой
1           Взрослый
2            Молодой
3            Молодой
4                NaN

In [91]:
new_rows = pd.DataFrame([{"Имя": "Дмитрий", "Возраст": 31, "Город": "Самара", "Страна":
"Россия"},
{"Имя": "Елена", "Возраст": 27, "Город": "Воронеж", "Страна":
"Россия"}
])
df = pd.concat([df, new_rows], ignore_index=True)
print(df)

       Имя  Возраст        Город  Страна  Возраст_в_месяцах  Зарплата  \
0     Анна       25       Москва  Россия              300.0   50000.0
1     Иван       30          СПб  Россия              360.0   60000.0
2    Ольга       22       Казань  Россия              264.0   45000.0
3     Петр       40  Новосибирск  Россия             5000.0     797.0
4  Алексей       29        Томск  Россия                NaN       NaN
5  Дмитрий       31       Самара  Россия                NaN       NaN
6    Елена       27      Воронеж  Россия                NaN       NaN

  Категория возраста
0            Молодой
1           Взрослый
2            Молодой
3            Молодой
4                NaN
5                NaN
6                NaN

In [95]:
df.loc["новый"] = ["Артем", 33, "Калуга", "Россия",3,3,0]
print(df)

           Имя  Возраст        Город  Страна  Возраст_в_месяцах  Зарплата  \
0         Анна       25       Москва  Россия              300.0   50000.0
1         Иван       30          СПб  Россия              360.0   60000.0
2        Ольга       22       Казань  Россия              264.0   45000.0
3         Петр       40  Новосибирск  Россия             5000.0     797.0
4      Алексей       29        Томск  Россия                NaN       NaN
5      Дмитрий       31       Самара  Россия                NaN       NaN
6        Елена       27      Воронеж  Россия                NaN       NaN
новый    Артем       33       Калуга  Россия                3.0       3.0

      Категория возраста
0                Молодой
1               Взрослый
2                Молодой
3                Молодой
4                    NaN
5                    NaN
6                    NaN
новый                  0

In [96]:
import pandas as pd
data = {
"Имя": ["Анна", "Иван", "Ольга"],
"Возраст": [25, 30, 22],
"Город": ["Москва", "СПб", "Казань"],
"Зарплата": [50000, 60000, 45000]
}
df = pd.DataFrame(data)
# Удаляем столбец "Зарплата"
df = df.drop(columns=["Зарплата"])
print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [97]:
df = df.drop(columns=["Возраст", "Город"])
print(df)

     Имя
0   Анна
1   Иван
2  Ольга

In [98]:
del df["Имя"]
print(df)

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [99]:
df["Имя"] = ["Анна", "Иван", "Ольга"] # Вернем столбец для примера
удаленный_столбец = df.pop("Имя")
print(удаленный_столбец)

0     Анна
1     Иван
2    Ольга
Name: Имя, dtype: object

In [100]:
df = pd.DataFrame(data) # Восстанавливаем DataFrame
# Удаляем строку с индексом 1 (Иван)
df = df.drop(index=1)
print(df)

     Имя  Возраст   Город  Зарплата
0   Анна       25  Москва     50000
2  Ольга       22  Казань     45000

In [101]:
df = df.drop(index=[0, 2]) # Удаляем Анну и Ольгу
print(df)

Empty DataFrame
Columns: [Имя, Возраст, Город, Зарплата]
Index: []

In [102]:
df = pd.DataFrame(data) # Восстанавливаем DataFrame
# Оставляем только людей старше 25 лет
df = df[df["Возраст"] > 25]
print(df)

    Имя  Возраст Город  Зарплата
1  Иван       30   СПб     60000

In [103]:
df = df.reset_index(drop=True) # Сбрасываем индексы
print(df)

    Имя  Возраст Город  Зарплата
0  Иван       30   СПб     60000

In [105]:
df.loc[3] = ["Мария", None, "Самара", 55000] # Добавим строку спропуском
df = df.dropna() # Удалим все строки с пропущенными значениями
print(df)

    Имя Возраст Город  Зарплата
0  Иван      30   СПб     60000

In [106]:
df = pd.DataFrame({
"Имя": ["Анна", "Иван", "Анна", "Ольга"],
"Возраст": [25, 30, 25, 22]
})
df = df.drop_duplicates()
print(df)

     Имя  Возраст
0   Анна       25
1   Иван       30
3  Ольга       22

In [108]:
df = df.drop_duplicates(subset=["Имя"])
print(df)

     Имя  Возраст
0   Анна       25
1   Иван       30
3  Ольга       22

In [109]:
import pandas as pd
data = {
"Имя": ["Анна", "Иван", "Ольга", "Петр", "Мария"],
"Возраст": [25, 30, 22, 40, 35],
"Город": ["Москва", "СПб", "Казань", "Новосибирск", "СПб"],
"Зарплата": [50000, 60000, 45000, 70000, 65000]
}
df = pd.DataFrame(data)
print(df)

     Имя  Возраст        Город  Зарплата
0   Анна       25       Москва     50000
1   Иван       30          СПб     60000
2  Ольга       22       Казань     45000
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000

In [110]:
df_filtered = df.query("Возраст > 30")
print(df_filtered)

     Имя  Возраст        Город  Зарплата
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000

In [111]:
df_filtered = df.query("Город == 'СПб' and Зарплата > 60000")
print(df_filtered)

     Имя  Возраст Город  Зарплата
4  Мария       35   СПб     65000

In [112]:
min_age = 25
df_filtered = df.query("Возраст > @min_age")
print(df_filtered)

     Имя  Возраст        Город  Зарплата
1   Иван       30          СПб     60000
3   Петр       40  Новосибирск     70000
4  Мария       35          СПб     65000

In [113]:
df_filtered = df[df["Город"].isin(["Москва", "СПб"])]
print(df_filtered)

     Имя  Возраст   Город  Зарплата
0   Анна       25  Москва     50000
1   Иван       30     СПб     60000
4  Мария       35     СПб     65000

In [114]:
df_filtered = df[~df["Город"].isin(["Москва", "СПб"])]
print(df_filtered)

     Имя  Возраст        Город  Зарплата
2  Ольга       22       Казань     45000
3   Петр       40  Новосибирск     70000

In [115]:
df_filtered = df[df["Возраст"].between(25, 35)]
print(df_filtered)

     Имя  Возраст   Город  Зарплата
0   Анна       25  Москва     50000
1   Иван       30     СПб     60000
4  Мария       35     СПб     65000

In [116]:
df_filtered = df[df["Возраст"].between(25, 35, inclusive="neither")]
print(df_filtered)

    Имя  Возраст Город  Зарплата
1  Иван       30   СПб     60000

In [117]:
import pandas as pd
data = {"Имя": ["Анна", "Иван", "Ольга", "Петр", None],
"Возраст": [25, 30, 22, None, 35],
"Город": ["Москва", "СПб", "Казань", "Новосибирск", "СПб"]
}
df = pd.DataFrame(data)
print(df)

     Имя  Возраст        Город
0   Анна     25.0       Москва
1   Иван     30.0          СПб
2  Ольга     22.0       Казань
3   Петр      NaN  Новосибирск
4   None     35.0          СПб

In [118]:
print(df.count())

Имя        4
Возраст    4
Город      5
dtype: int64

In [119]:
print(df["Город"].value_counts())

Город
СПб            2
Москва         1
Казань         1
Новосибирск    1
Name: count, dtype: int64

In [120]:
print(df["Город"].value_counts(sort=False))

Город
Москва         1
СПб            2
Казань         1
Новосибирск    1
Name: count, dtype: int64

In [121]:
print(df["Имя"].value_counts(dropna=False))

Имя
Анна     1
Иван     1
Ольга    1
Петр     1
None     1
Name: count, dtype: int64

In [122]:
print(df.nunique())

Имя        4
Возраст    4
Город      4
dtype: int64

In [123]:
print(df["Имя"].nunique(dropna=False))

5

In [124]:
print(df.isna().sum())

Имя        1
Возраст    1
Город      0
dtype: int64

In [125]:
import pandas as pd
data = {
"Имя": ["Анна", "Иван", "Ольга", "Петр", "Мария"],
"Возраст": [25, 30, 22, 40, 35],
"Зарплата": [50000, 60000, 45000, 70000, 65000]
}
df = pd.DataFrame(data)
print(df)

     Имя  Возраст  Зарплата
0   Анна       25     50000
1   Иван       30     60000
2  Ольга       22     45000
3   Петр       40     70000
4  Мария       35     65000

In [126]:
df_sorted = df.sort_values(by="Возраст")
print(df_sorted)

     Имя  Возраст  Зарплата
2  Ольга       22     45000
0   Анна       25     50000
1   Иван       30     60000
4  Мария       35     65000
3   Петр       40     70000

In [127]:
df_sorted = df.sort_values(by="Возраст", ascending=False)
print(df_sorted)

     Имя  Возраст  Зарплата
3   Петр       40     70000
4  Мария       35     65000
1   Иван       30     60000
0   Анна       25     50000
2  Ольга       22     45000

In [128]:
df_sorted = df.sort_values(by=["Возраст", "Зарплата"], ascending=
[True, False])
print(df_sorted)

     Имя  Возраст  Зарплата
2  Ольга       22     45000
0   Анна       25     50000
1   Иван       30     60000
4  Мария       35     65000
3   Петр       40     70000

In [129]:
df.loc[5] = ["Елена", None, 55000] # Добавляем строку с NaN в
"Возраст"
df_sorted = df.sort_values(by="Возраст", na_position="first")
print(df_sorted)

     Имя Возраст  Зарплата
5  Елена    None     55000
2  Ольга      22     45000
0   Анна      25     50000
1   Иван      30     60000
4  Мария      35     65000
3   Петр      40     70000

In [130]:
df_sorted = df.sort_index()
print(df_sorted)

     Имя Возраст  Зарплата
0   Анна      25     50000
1   Иван      30     60000
2  Ольга      22     45000
3   Петр      40     70000
4  Мария      35     65000
5  Елена    None     55000

In [131]:
df_sorted = df.sort_index(ascending=False)
print(df_sorted)

     Имя Возраст  Зарплата
5  Елена    None     55000
4  Мария      35     65000
3   Петр      40     70000
2  Ольга      22     45000
1   Иван      30     60000
0   Анна      25     50000

In [132]:
df = pd.DataFrame({
"Имя": ["Анна", "Иван", "Ольга"],
"Возраст": [25, 30, 22],
"Город": ["Москва", "СПб", "Казань"]
})
print(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [133]:
from IPython.display import display
display(df)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [134]:
df.head(5)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [135]:
df.tail(3)

     Имя  Возраст   Город
0   Анна       25  Москва
1   Иван       30     СПб
2  Ольга       22  Казань

In [136]:
pd.set_option("display.max_rows", 100)

In [137]:
pd.set_option("display.max_columns", 50)

In [138]:
pd.set_option("display.max_colwidth", None)

In [139]:
pd.set_option("display.float_format", "{:.2f}".format)

In [140]:
df.style.set_sticky()

In [141]:
import qgrid
qgrid_widget = qgrid.show_grid(df, show_toolbar=True)
qgrid_widget

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': True, 'defau…

In [142]:
from tabulate import tabulate
print(tabulate(df, headers="keys", tablefmt="github"))

|    | Имя   |   Возраст | Город   |
|----|-------|-----------|---------|
|  0 | Анна  |        25 | Москва  |
|  1 | Иван  |        30 | СПб     |
|  2 | Ольга |        22 | Казань  |

In [143]:
df.style.set_properties(**{"background-color": "lightgray", "color":
"black"})

In [145]:
html_table = df.to_html(\)
with open("table.html", "w", encoding="utf-8") as f:
f.write(html_table)

IndentationError: expected an indented block after 'with' statement on line 2 (4265293143.py, line 3)